# Generated by Django 5.0.4 on 2024-05-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "finder",
            "0007_bellysymptoms_footsymptoms_handsymptoms_headsymptoms_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BellyPelvisSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HeadUpperSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
    ]
