# Generated by Django 5.0.4 on 2024-05-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
                ("head", models.CharField(blank=True, max_length=100, null=True)),
                ("upperbody", models.CharField(blank=True, max_length=100, null=True)),
                ("belly", models.CharField(blank=True, max_length=100, null=True)),
                ("pelvis", models.CharField(blank=True, max_length=100, null=True)),
                ("arm", models.CharField(blank=True, max_length=100, null=True)),
                ("onlyarm", models.CharField(blank=True, max_length=100, null=True)),
                ("hand", models.CharField(blank=True, max_length=100, null=True)),
                ("leg", models.CharField(blank=True, max_length=100, null=True)),
                ("onlyleg", models.CharField(blank=True, max_length=100, null=True)),
                ("foot", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranlatedDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Disease", models.CharField(max_length=100)),
                ("Symptom_1", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_2", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_3", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_4", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_5", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_6", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_7", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_8", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_9", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_10", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_11", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_12", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_13", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_14", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_15", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_16", models.CharField(blank=True, max_length=100, null=True)),
                ("Symptom_17", models.CharField(blank=True, max_length=100, null=True)),
                ("Hospital", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
