# Generated by Django 5.0.4 on 2024-05-11 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0002_symptom_tranlateddisease"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TranlatedDisease",
            new_name="TranslatedDisease",
        ),
    ]
