# Generated by Django 5.0.4 on 2024-05-14 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0003_rename_tranlateddisease_translateddisease"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.DeleteModel(
            name="TranslatedDisease",
        ),
    ]
