# Generated by Django 5.0.4 on 2024-05-17 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0005_disease"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symptom",
            name="arm",
        ),
        migrations.RemoveField(
            model_name="symptom",
            name="leg",
        ),
    ]
