# Generated by Django 5.0.4 on 2024-05-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finder", "0006_remove_symptom_arm_remove_symptom_leg"),
    ]

    operations = [
        migrations.CreateModel(
            name="BellySymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FootSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HandSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HeadSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OnlyArmSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OnlyLegSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PelvisSymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UpperbodySymptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptom", models.CharField(max_length=100)),
            ],
        ),
    ]
